version: '3.4'
services:
  bd_cvseguroapp:
    container_name: bd_cvseguroapp
    build:
      context: .
      dockerfile: DockerfileMongo
    ports:
      - 27017:27017
    volumes:
    # CUALQUIER BD QUE SE CREE EN MONGO SE VA A GUARDAR EN ESE DIRECTORIO 
    # 
      - $PWD/../BD_CVSEGUROAPP:/data/db 
    networks:
      - cvseguro-net

  

networks:
  cvseguro-net: